name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.host }}-latest

    strategy:
      matrix:
        host: [ubuntu, windows]

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          case "${{ matrix.host }}" in
            ubuntu)
              sudo apt-get install --yes g++-10 cmake ninja-build
              export CC=gcc-10 CXX=g++-10
              ;;
            windows)
              choco install ninja
              ;;
          esac
          cmake v3 -G Ninja

      - name: Build
        run: |
          cmake --build .

      - name: Run
        run: |
          cmake -E env ./hello
